SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS =0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS =0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE ='TRADITIONAL';

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
` NUMBER ` INT(11) NOT NULL,
`started` DATETIME NULL DEFAULT NULL ,
`finished` DATETIME NULL DEFAULT NULL,
`scheduled` DATETIME NOT NULL,
`lastChange` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`) ,
UNIQUE INDEX `UNIQUE_ENTITY` (` NUMBER ` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_division` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
`tourney` BIGINT(20) NOT NULL,
` LANGUAGE ` INT(11) NOT NULL,
` SECTION ` INT(11) NOT NULL,
`started` DATETIME NULL DEFAULT NULL ,
`finished` DATETIME NULL DEFAULT NULL,
`activeRound` INT(11) NOT NULL,
`lastChange` TIMESTAMP NULL DEFAULT NULL ,
PRIMARY KEY (`id`) ,
UNIQUE INDEX `UNIQUE_ENTITY` (`tourney` ASC, ` LANGUAGE ` ASC, ` SECTION ` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_round` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
` NUMBER ` INT(11) NOT NULL,
`division` BIGINT(20) NOT NULL,
`totalGamesCount` INT(11) NOT NULL,
`finishedGamesCount` INT(11) NULL DEFAULT NULL,
`started` DATETIME NULL DEFAULT NULL,
`finished` DATETIME NULL DEFAULT NULL,
`lastChange` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`) ,
UNIQUE INDEX `UNIQUE_ENTITY` (` NUMBER ` ASC, `division` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_group` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
` NUMBER ` INT(11) NOT NULL,
`round` BIGINT(20) NOT NULL,
`playersCount` TINYINT(4) NULL DEFAULT NULL,
`player1` BIGINT(20) NULL DEFAULT NULL,
`player2` BIGINT(20) NULL DEFAULT NULL,
`player3` BIGINT(20) NULL DEFAULT NULL,
`player4` BIGINT(20) NULL DEFAULT NULL,
`scores1` TINYINT(4) NULL DEFAULT NULL,
`scores2` TINYINT(4) NULL DEFAULT NULL,
`scores3` TINYINT(4) NULL DEFAULT NULL,
`scores4` TINYINT(4) NULL DEFAULT NULL,
`game1` BIGINT(20) NULL DEFAULT NULL,
`game2` BIGINT(20) NULL DEFAULT NULL,
`game3` BIGINT(20) NULL DEFAULT NULL,
`game4` BIGINT(20) NULL DEFAULT NULL,
`game5` BIGINT(20) NULL DEFAULT NULL,
`game6` BIGINT(20) NULL DEFAULT NULL,
`started` DATETIME NULL DEFAULT NULL,
`finished` DATETIME NULL DEFAULT NULL,
`lastChange` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`) ,
UNIQUE INDEX `UNIQUE_ENTITY` (` NUMBER ` ASC, `round` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_config` (
`id` BIGINT(20) NOT NULL,
`lastTourneyCheck` TIMESTAMP NULL DEFAULT NULL ,
`lastDivisionCheck` TIMESTAMP NULL DEFAULT NULL,
`lastRoundCheck` TIMESTAMP NULL DEFAULT NULL,
`lastGroupCheck` TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_round_copy1` (
`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
` NUMBER ` INT(11) NOT NULL,
`division` BIGINT(20) NOT NULL,
`totalGamesCount` INT(11) NOT NULL,
`finishedGamesCount` INT(11) NULL DEFAULT NULL,
`started` DATETIME NULL DEFAULT NULL,
`finished` DATETIME NULL DEFAULT NULL,
PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `wisematches`.`tourney_regular_subs` (
`player` BIGINT(20) NOT NULL,
`tourney` INT(11) NOT NULL,
`round` INT(11) NOT NULL,
` LANGUAGE ` INT(11) NULL DEFAULT NULL,
` SECTION ` INT(11) NULL DEFAULT NULL,
PRIMARY KEY (`player`, `tourney`, `round`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

DROP TABLE IF EXISTS `wisematches`.`tournament_request`;

DROP TABLE IF EXISTS `wisematches`.`tournament_announce`;

DROP TABLE IF EXISTS `wisematches`.`tournament`;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
