[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="personality" type="wisematches.core.Personality" --]
[#-- @ftlvariable name="messageSource" type="wisematches.playground.GameMessageSource" --]
[#-- @ftlvariable name="statisticsManager" type="wisematches.playground.tracking.StatisticsManager" --]