CREATE  TABLE IF NOT EXISTS `wisematches`.`scribble_comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `board` BIGINT(20) NULL DEFAULT NULL ,
  `person` BIGINT(20) NULL DEFAULT NULL ,
  `text` VARCHAR(254) NULL DEFAULT NULL ,
  `creationDate` TIMESTAMP NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;