[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="language" type="wisematches.core.Language" --]
[#-- @ftlvariable name="staticDomain" type="java.lang.String" --]
[#-- @ftlvariable name="serverHostname" type="java.lang.String" --]
[#-- @ftlvariable name="principal" type="wisematches.core.Personality" --]
[#-- @ftlvariable name="playerManager" type="wisematches.core.personality.player.MemberManager" --]
[#-- @ftlvariable name="playerStateManager" type="wisematches.server.web.services.state.PlayerStateManager" --]
[#-- @ftlvariable name="captchaService" type="wisematches.server.web.security.captcha.CaptchaService" --]
[#-- @ftlvariable name="advertisementManager" type="wisematches.server.web.services.ads.AdvertisementManager" --]
[#-- @ftlvariable name="gameMessageSource" type="wisematches.server.web.i18n.GameMessageSource" --]

[#-- @ftlvariable name="Language" type="wisematches.core.Language.static" --]
[#-- @ftlvariable name="AwardType" type="wisematches.server.services.award.AwardType.static" --]
[#-- @ftlvariable name="Membership" type="wisematches.core.PlayerType.static" --]
