[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="locale" type="java.util.Locale" --]
[#-- @ftlvariable name="language" type="wisematches.personality.Language" --]
[#-- @ftlvariable name="serverHostname" type="java.lang.String" --]
[#-- @ftlvariable name="principal" type="wisematches.personality.player.Player" --]
[#-- @ftlvariable name="playerManager" type="wisematches.personality.player.PlayerManager" --]
[#-- @ftlvariable name="playerStateManager" type="wisematches.server.web.services.state.PlayerStateManager" --]
[#-- @ftlvariable name="captchaService" type="wisematches.server.web.security.captcha.CaptchaService" --]
[#-- @ftlvariable name="advertisementManager" type="wisematches.server.web.services.ads.AdvertisementManager" --]
[#-- @ftlvariable name="gameMessageSource" type="wisematches.server.web.i18n.GameMessageSource" --]

[#-- @ftlvariable name="Language" type="wisematches.personality.Language.static" --]
[#-- @ftlvariable name="Membership" type="wisematches.personality.Membership.static" --]
[#-- @ftlvariable name="AwardType" type="wisematches.playground.award.AwardType.static" --]
